### ISSUE TITLE
Tracking: Unsupported Symbols

### ISSUE THREAD

**Issue by CraftSpider** [whitequark/python-itanium_demangler#5]
List of known symbols that don't work due to either bugs or missing parts of the standard. Only one example is provided for each issue.

- [x] Transaction Clone special name: `_ZGTtNKSt9exceptionD1Ev` -> `transaction clone for std::exception::~exception() const`
- [x] Method pointers aren't supported: `_ZNSt15__exception_ptr13exception_ptrC1EMS0_FvvE` -> `std::__exception_ptr::exception_ptr::{ctor}(void (std::__exception_ptr::exception_ptr::*)())`
- [x] Guard Variable special name: `_ZGVNSt7__cxx1110moneypunctIcLb0EE2idE` -> `guard variable for std::__cxx11::moneypunct<char, false>::id`

**Comment by CraftSpider** [comment]
I will PR at least two of these soon hopefully, the other two will require more thought
